[package]

name = "gfx_debug_draw"
version = "0.7.0"
authors = ["Steve Jahns <s.t.jahns@gmail.com>"]
keywords = ["draw", "gfx", "debug", "piston"]
description = "Debug rendering library for gfx-rs"
license = "MIT"
readme = "README.md"
repository = "https://github.com/PistonDevelopers/gfx-debug-draw"
homepage = "https://github.com/PistonDevelopers/gfx-debug-draw"

[lib]

name = "gfx_debug_draw"
path = "src/lib.rs"

[dependencies]

gfx = "0.8.0"
gfx_text = "^0.6.0"
vecmath = "0.2.0"

###### For example ###########################

[dev-dependencies]

piston = "*"
piston_window = "0.27.0"
sdl2 = "*"
pistoncore-sdl2_window = "0.16.0"
gfx_device_gl = "*"
shader_version = "*"
camera_controllers = "*"
current = "0.1.1"

###############################################
