[package]

name = "gfx_debug_draw"
version = "0.3.0"
authors = ["Steve Jahns <s.t.jahns@gmail.com>"]
keywords = ["draw", "gfx", "debug"]
description = "Debug rendering library for gfx-rs"
license = "MIT"
readme = "README.md"
repository = "https://github.com/PistonDevelopers/gfx_debug_draw"
homepage = "https://github.com/PistonDevelopers/gfx_debug_draw"

[lib]

name = "gfx_debug_draw"
path = "src/lib.rs"

[dependencies]

gfx = "0.6.*"
gfx_text = "^0.3.1"
vecmath = "*"

###### For example ###########################

[dev-dependencies]

piston = "0.1.*"
piston_window = "0.0.*"
sdl2 = "0.4.*"
pistoncore-sdl2_window = "0.0.*"
gfx_device_gl = "0.4.*"
shader_version = "0.0.*"
camera_controllers = "0.0.*"

###############################################
