[package]

name = "gfx_debug_draw"
version = "0.12.0"
authors = ["Steve Jahns <s.t.jahns@gmail.com>"]
keywords = ["draw", "gfx", "debug", "piston"]
description = "Debug rendering library for gfx-rs"
license = "MIT"
readme = "README.md"
repository = "https://github.com/PistonDevelopers/gfx-debug-draw"
homepage = "https://github.com/PistonDevelopers/gfx-debug-draw"

[lib]

name = "gfx_debug_draw"
path = "src/lib.rs"

[dependencies]

gfx = "0.13.0"
gfx_text = "0.14.0"
vecmath = "0.2.0"

###### For example ###########################

[dev-dependencies]

piston = "0.27.0"
piston_window = "0.61.0"
sdl2 = "0.27.2"
pistoncore-sdl2_window = "0.38.0"
gfx_device_gl = "0.12.0"
shader_version = "0.2.1"
camera_controllers = "0.18.0"
current = "0.1.2"

###############################################
