[package]

name = "gfx_debug_draw"
version = "0.16.0"
authors = ["Steve Jahns <s.t.jahns@gmail.com>"]
keywords = ["draw", "gfx", "debug", "piston"]
description = "Debug rendering library for gfx-rs"
license = "MIT"
readme = "README.md"
repository = "https://github.com/PistonDevelopers/gfx-debug-draw"
homepage = "https://github.com/PistonDevelopers/gfx-debug-draw"

[lib]

name = "gfx_debug_draw"
path = "src/lib.rs"

[dependencies]

gfx = "0.16.0"
gfx_text = "0.17.0"
vecmath = "0.3.0"

###### For example ###########################

[dev-dependencies]

piston = "0.33.0"
piston_window = "0.70.0"
sdl2 = "0.30.0"
pistoncore-sdl2_window = "0.44.0"
gfx_device_gl = "0.14.0"
shader_version = "0.2.1"
camera_controllers = "0.22.0"
current = "0.1.2"

###############################################
