[package]

name = "gfx_debug_draw"
version = "0.2.0"
authors = ["Steve Jahns <s.t.jahns@gmail.com>"]

[dependencies]
gfx = "0.6.*"
gfx_text = "0.2.*"
vecmath = "*"

###### For example ###########################

[dev-dependencies]
piston = "0.1.*"
piston_window = "0.0.*"
sdl2 = "0.4.*"
pistoncore-sdl2_window = "0.0.*"
gfx_device_gl = "0.4.*"
shader_version = "0.0.*"
camera_controllers = "0.0.*"

###############################################
